services:
  - type: web
    name: my-flask-app
    env: python
    pythonVersion: "3.10"
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true