services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    region: oregon  # choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true